# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='UserReg',
        ),
    ]
